### ISSUE TITLE
What is certificate_thumbprint?

### ISSUE THREAD

**Issue by Kotoki1337** [MinisBett/ultimate-osu-server-switcher#1]
Just like the title. Although I know a little bit, I still want to ask, if I want to add a server to the data, how do I fill in the thumbprint part same as u guys? im worried that the thumbprint I got from other ways will be different from yours

**Comment by MinisBett** [comment]
The thumbprint is a seemingly unique id for the certificate.

You can get it by using our [certificate thumbprint reader](https://github.com/MinisBett/ultimate-osu-server-switcher/tree/master/CertificateThumbprintReader) tool. Paste in the certificate, click on get thumbprint and use the output as the thumbprint.

Give me a couple minutes, I will release the thumbprint reader so you don't have to compile it.

If the program cannot read your certificate, make sure its not encoded with base64.

**Comment by Julaaaan** [comment]
I added the thumbprint reader to the current 1.0 release.
