### ISSUE TITLE
Server Request

### ISSUE THREAD

**Issue by troke12** [MinisBett/ultimate-osu-server-switcher#11]
yo, i wanna try this, so this is information about my server

- The server name : Datenshi
- The server website url : [Datenshi](https://datenshi.xyz)
- The server ip address : 139.99.88.243
- The certificates : [cert.cer](https://old.datenshi.xyz/cert.cer)
- The discord tag of the server owner : troke.id#0027
- The certificate thumbprint : 1CC98B7AA832873E6B8B8C40FB24EEDB296AC2E6
- The server icon : ![icon](https://old.datenshi.xyz/logo-48x48.png) (48x48)

**Comment by MinisBett** [comment]
Please give us an icon that has the size of 48x48 pixels.

**Comment by troke12** [comment]
Updated

**Comment by MinisBett** [comment]
Please convert your .cer certificate to a .crt certificate as specified in the README.md

**Comment by troke12** [comment]
here https://old.datenshi.xyz/cert.crt
