### ISSUE TITLE
New Misumi certificate

### ISSUE THREAD

**Issue by lenforiee** [MinisBett/ultimate-osu-server-switcher#12]
We recently updated certificate so can you update it, cheers

New certificate: [cert.cer](http://admin.misumi.me/static/cert.cer)

**Comment by zukyoo** [comment]
Wasn't 100% sure if above is updated so here is new thumbprint and .cer file:

Thumbprint: 142BB234C91877E240957A297DA407AFD5D4C835
[Certificate](https://admin.misumi.me/static/cert.cer)

**Comment by MinisBett** [comment]
Changed.
