### ISSUE TITLE
StreamCompanion crashes when restarting osu! using the switcher

### ISSUE THREAD

**Issue by MinisBett** [MinisBett/ultimate-osu-server-switcher#15]
If osu! is restarted by the switcher osu automatically has administrative privilages.
Due to this, stream companion is no longer able to access the osu process.

A fix would be either starting osu manually or starting stream companion as an admin.

**Comment by jy1263** [comment]
not sure as to how buggy this solution is, but MS has a script for running stuff unelevated in their "nodejs tools for visual studio" repository: https://stackoverflow.com/a/58646320

**Comment by MinisBett** [comment]
Will investigate into @jy1263 comment. //closed
