### ISSUE TITLE
server request

### ISSUE THREAD

**Issue by Nerina1241** [MinisBett/ultimate-osu-server-switcher#24]
- The server name: Debian
- The server’s website url: https://debian.moe/
- The server’s ip-address: 49.165.136.97
- The certificate: https://debian.moe/static/cert.cer
- The discord tag of the server owner: Nerina#4444
- The certificate thumbprint: 350fce0f2a489229928e2ec7dc2b426b49192f16
- The server icon: https://debian.moe/static/44x44.png

**Comment by MinisBett** [comment]
I will add the server in approx. about 21 hours. Keep in mind that the datav1 format will be deprecated and no longer maintained when the new switcher V2 comes out with the brand new mirror based datav2 format.

**Comment by MoonFoxy** [comment]
Why the name of the operating system

**Comment by Nerina1241** [comment]
> Why the name of the operating system

cuz debian is so very better any other os

**Comment by Lukumiya** [comment]
> > Why the name of the operating system
> 
> cuz debian is so very better any other os

Im using arch btw

**Comment by MinisBett** [comment]
I need a 48x48 icon

**Comment by Nerina1241** [comment]
> I need a 48x48 icon

https://debian.moe/static/48x48.png here
