### ISSUE TITLE
Linux/Ubuntu support?

### ISSUE THREAD

**Issue by saieeshb** [MinisBett/ultimate-osu-server-switcher#25]
I'm on Linux and this would be great since you have to manually install and delete Certificates in Wine and most of the time it doesn't even install. This would make it a 100x simpler to switch servers :)

**Comment by MinisBett** [comment]
This is not doable for me for various reasons.

1. I don't know Linux nor its mechanics at all so I neither know how to install certificates nor what the equivalent of the hosts file would be.

2. The program is made in C# using the .NET Framework and WinForms. Even though .NET (Core) exists and has a full implementation of WinForms it still only runs on windows.

3. I could make an application that can run on both Windows and Linux but that would force me to learn Linux and Xamarin and thats nothing you do in 1 day. Building an application like the UOSS would take approx. 1-2 years for me.

I am very sorry I cannot provide this handy tool to you.
Just don't use Linux. Use Windows.
