### ISSUE TITLE
Server Request

### ISSUE THREAD

**Issue by Mxnuuel** [MinisBett/ultimate-osu-server-switcher#26]
Name: Horizon
Website url: https://lemres.de/
ip-address: 5.189.146.179
Certificate: https://x.mxnuuel.de/horizon.cer
Discord tag of the owner: Lemres#0001
Thumbprint: 5dbe360599200f97954fd3d0f4d183dcce20f5b1
Icon: https://lemres.de/static/44x44.png

**Comment by MinisBett** [comment]
The icon needs to be 48x48

**Comment by Mxnuuel** [comment]
Oh i'm sorry that's completly my bad since i missread that!
https://lemres.de/static/48x48.png

**Comment by MinisBett** [comment]
its 48x49 lol

**Comment by MinisBett** [comment]
added.
