### ISSUE TITLE
Server Request

### ISSUE THREAD

**Issue by mbruhyo** [MinisBett/ultimate-osu-server-switcher#27]
Server Name: Aisuru
Website URL: aisuru.xyz
IP Address: 18.132.248.125
Certificate: https://admin.aisuru.xyz/static/cert.cer
Discord Tag: mbruhyo#8551
Thumbprint: 0A2DD2632412D829FAA9DF7BDD59DB3200F7F847
48x48 Icon: https://i.imgur.com/QgqJVFD.png

**Comment by MinisBett** [comment]
Does your server still exist? Cant connect
