### ISSUE TITLE
server request

### ISSUE THREAD

**Issue by DeanHerbertPeppy** [MinisBett/ultimate-osu-server-switcher#28]
nekosu
https://nekosu.cf/
77.68.124.198
https://drive.google.com/file/d/1VCeHgie5W1KktdYzE_tJQtipf6HkExwN/view?usp=sharing    (certificate)
Mattyosu ♡#0001
5dbe360599200f97954fd3d0f4d183dcce20f5b1 (thumbprint)
(server logo 48x48)
![dgdfg1](https://user-images.githubusercontent.com/73605518/102940288-43f51480-44b0-11eb-9b9c-82a6eda5ab79.png)

**Comment by Mattyosu** [comment]
Mattyosu ♡#0001 not Mattyosu ♡#1 lmao

**Comment by Mattyosu** [comment]
wtf why did it correct to #1 not 0001

**Comment by MinisBett** [comment]
server was added.
