### ISSUE TITLE
Add Misumi

### ISSUE THREAD

**Issue by zukyoo** [MinisBett/ultimate-osu-server-switcher#3]
(featured server btw, I am dev here)

Server name: Misumi
Server URL: https://misumi.me
Server IP: 5.83.161.92
Server certificate: https://cdn.discordapp.com/attachments/712147691366253036/713330720948617267/cert_2.crt
Server certificate thumbprint: C386F82BC66A296A78B399C9F087D0206218E283
Logo (48x48): https://files.theosurealm.tk/o6yb.png

**Comment by zukyoo** [comment]
If you need the .cer version for the certificate:

https://files.theosurealm.tk/AaoE.cer

**Comment by MinisBett** [comment]
Added.
