### ISSUE TITLE
server request

### ISSUE THREAD

**Issue by tsunyoku** [MinisBett/ultimate-osu-server-switcher#30]
name: iteki
url: https://iteki.pw
ip: 144.91.70.152
cert: https://iteki.pw/static/iteki.cer
dc tag: mbruhyo#8551
cert thumbprint: AB64A3CE05AA28C0A24EE1DD322E85B36C27620F
icon: https://i.imgur.com/TR09ojM.png

**Comment by tsunyoku** [comment]
oh and for V2 switcher, here: https://switcher.iteki.pw/uoss

**Comment by MinisBett** [comment]
Why does this link have no file extension? I need to have a url where ".json" is at the end (e.g. https://iteki.pw/static/uoss.json)

**Comment by MinisBett** [comment]
Server was fucked.
