### ISSUE TITLE
Server request

### ISSUE THREAD

**Issue by Gunnest663** [MinisBett/ultimate-osu-server-switcher#31]
Name: Miksu!
Url: https://miksu.pw/
IP: 45.77.48.146
Cert: https://switcher.miksu.pw/cert.cer
Discord: Gunnest663#0001
Json file: https://switcher.miksu.pw/uoss.json
Cert thumbprint: 5dbe360599200f97954fd3d0f4d183dcce20f5b1
Icon: https://switcher.miksu.pw/icon.png

**Comment by MinisBett** [comment]
Added to Switcher V2.

**Comment by MinisBett** [comment]
Please add me on Discord or join our Discord server, you can find it in the README file.
