### ISSUE TITLE
Server request

### ISSUE THREAD

**Issue by alowave223** [MinisBett/ultimate-osu-server-switcher#34]
Name: Sakuru
Url: https://osu.sakuru.pw/
IP: 75.119.129.110
Discord Tag: alowave#2018
Cert: https://osu.sakuru.pw/static/cert.cer
Json file: https://osu.sakuru.pw/static/uoss.json
Cert thumbprint: 5DBE360599200F97954FD3D0F4D183DCCE20F5B1
Icon: https://osu.sakuru.pw/static/64.png

**Comment by MinisBett** [comment]
Server dead.
