### ISSUE TITLE
server request

### ISSUE THREAD

**Issue by Kapitar** [MinisBett/ultimate-osu-server-switcher#41]
1. hanasu
2. hanasu.pw
3. 94.228.123.168
4. https://drive.google.com/file/d/1E0bpqxrTomFMLX3JQpMade30W4Nvf4Xy/view?usp=sharing
5. kapitar#1337
6. D47FEFEF9898C4244103E920E7EC76D2B50F1975
7. 
![logo](https://user-images.githubusercontent.com/52191611/124742963-ea24db00-df25-11eb-95f8-d6528a301664.png)

**Comment by MinisBett** [comment]
Issue was resolved.
