### ISSUE TITLE
Server Request

### ISSUE THREAD

**Issue by RealistikDash** [MinisBett/ultimate-osu-server-switcher#5]
Name: RealistikOsu!
URL: https://ussr.pl
Server IP: 95.179.225.194
Thumbprint: F3188CAA6D3F724F63E7AB4772AE6796C7EF9646
Certificate: http://dl.ussr.pl/files/other/rosucer.cer
Logo: http://dl.ussr.pl/files/other/rosulogox48.png

**Comment by MinisBett** [comment]
Added.

Make sure to join our [discord server](https://minisbett.github.io/ultimate-osu-server-switcher/discord) to stay up-to-date.
