### ISSUE TITLE
github question osu

### ISSUE THREAD

**Issue by kalil1121** [MinisBett/ultimate-osu-server-switcher#6]
hello, i wanted to make a private server osu with the program, i will be so grateful if you can help me.

**Comment by RealistikDash** [comment]
This program does not create private servers. This is just a multi server switcher. It allows people to quickly switch between servers.

**Comment by kalil1121** [comment]
lol, im so idiot, thanks

**Comment by MinisBett** [comment]
As @RealistikDash already said this program allows you to switch between a variety of osu private servers.

But thanks for your interest in that program.
