### ISSUE TITLE
Enjuu

### ISSUE THREAD

**Issue by JustinOsu** [MinisBett/ultimate-osu-server-switcher#7]
Servername: Enjuu
URL: https://enjuu.click/
IP: 148.251.234.42
Owner: Justin | Enjuu#3716 (201632705723629568)
Thumbprint: 79889565CA264254A678D6836BB8DDBCB1F54661
Cert: https://onii-chan-please.come-inside.me/2020-06-02_21-30-22.cer
Logo: https://onii-chan-please.come-inside.me/2020-06-02_21-21-19.png

**Comment by Julaaaan** [comment]
Added.
Thanks for being part of our switcher!

**Comment by i-yitsure** [comment]
pogchamp
