### ISSUE TITLE
Server Request

### ISSUE THREAD

**Issue by r33int** [MinisBett/ultimate-osu-server-switcher#8]
Hi, here is the required information for adding the server Kawata.

- The server name: Kawata

- The server’s website url: https://kawata.pw/

- The server’s ip-address: 88.198.32.214

- The certificate: https://paste.hifumi.us/?e37e12682fa6c6dc#85AQsEnhGmo1Tk4b1W6RBHqakSMbRst6vxHfkgC6rvrg

- The discord tag of the server owner: r3#8700

- The certificate thumbprint: 2B2172601AB162E0ACF7EB829BE29C9FD7907E91

- The server icon: https://i.imgur.com/FuJCHdG.png

**Comment by Hazuki-san** [comment]
pog

**Comment by MinisBett** [comment]
Added.
Thanks for being a part of our switcher!
